---
name: Feature request
description: Suggest an improvement
title: "[Feature]: "
labels:
  - enhancement
body:
  - type: input
    id: problem
    attributes:
      label: Problem statement
      description: What problem are you solving?
      placeholder: As a maintainer, I need ...
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: Describe the desired behavior and scope
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Optional alternatives and trade-offs
    validations:
      required: false
  - type: textarea
    id: validation
    attributes:
      label: Validation plan
      description: How should we verify completion?
      placeholder: typecheck, tests, build, smoke path
    validations:
      required: true
